import type { Metadata } from "next";
import "./globals.scss";
import "design-system-zeroz/dist/index.esm.css";
import "design-system-zeroz/src/scss/tokens/tokens.scss";
import Header from "@/components/header/header";

export const metadata: Metadata = {
  title: "Evandro Metz",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR" data-company="whitelabel" data-theme="dark">
      <body>
        <Header />
        {children}
      </body>
    </html>
  );
}
